test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -177,71 +177,71 @@ jobs:
   deploy_back:
     runs-on: ubuntu-latest
 
-    steps:
-      - name: checkout repository
-        uses: actions/checkout@v4
+  steps:
+    - name: checkout repository
+      uses: actions/checkout@v4
 
-      - name: Add SSH key
-        uses: webfactory/ssh-agent@v0.5.4
-        with:
-          ssh-private-key: ${{ secrets.EC2_KEY }}
+    - name: Add SSH key
+      uses: webfactory/ssh-agent@v0.5.4
+      with:
+        ssh-private-key: ${{ secrets.EC2_KEY }}
 
-      - name: Ensure SSH directory exists
-        run: |
-          mkdir -p ~/.ssh
-          chmod 700 ~/.ssh
+    - name: Ensure SSH directory exists
+      run: |
+        mkdir -p ~/.ssh
+        chmod 700 ~/.ssh
 
-      - name: Add SSH known hosts
-        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+    - name: Add SSH known hosts
+      run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
-      - name: Install Dependencies of Back
-        working-directory: ./backend
-        run: npm i
+    - name: Install Dependencies of Back
+      working-directory: ./backend
+      run: npm i
 
-      - name: create .env file
-        run: |
-          echo "${{ secrets.SERVER_ENV }}" | sed 's/:/\n/g' > .env
+    - name: create .env file
+      run: |
+        echo "${{ secrets.SERVER_ENV }}" | sed 's/:/\n/g' > .env
 
-      - name: Build Back
-        working-directory: ./backend
-        run: npx tsc --noEmit
+    - name: Build Back
+      working-directory: ./backend
+      run: npx tsc
 
-      - name: Copy Files to EC2
-        run: |
-          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
-            rm -rf /var/www/backend
-            mkdir /var/www/backend'
-          rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
-          rsync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
-          rsync -avz -e "ssh" .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/.env
+    - name: Copy Files to EC2
+      run: |
+        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          rm -rf /var/www/backend
+          mkdir /var/www/backend'
+        rsync -avz -e "ssh" ./server/build/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend
+        rsync -avz -e "ssh" ./server/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/package.json
+        rsync -avz -e "ssh" .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/.env
 
-      - name: Install and Configure Node.js and PM2
-        run: |
-          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
-            export NVM_DIR="$HOME/.nvm"
-            if [ -s "$NVM_DIR/nvm.sh" ]; then
-              . "$NVM_DIR/nvm.sh"
-            else 
-              echo "nvm.sh not found"
-              exit 1
-            fi
-            nvm use --lts
-            cd /var/www/backend
-            npm i --production
-          '
+    - name: Install and Configure Node.js and PM2
+      run: |
+        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          export NVM_DIR="$HOME/.nvm"
+          if [ -s "$NVM_DIR/nvm.sh" ]; then
+            . "$NVM_DIR/nvm.sh"
+          else 
+            echo "nvm.sh not found"
+            exit 1
+          fi
+          nvm use --lts
+          cd /var/www/backend
+          npm i --production
+        '
 
-      - name: Start Server
-        run: |
-          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
-            export NVM_DIR="$HOME/.nvm"
-            if [ -s "$NVM_DIR/nvm.sh" ]; then
-              . "$NVM_DIR/nvm.sh"
-            else 
-              echo "nvm.sh not found"
-              exit 1
-            fi
-            nvm use --lts
-            npm install -g pm2
-            pm2 stop all
-            pm2 start /var/www/backend/index.js --name backend
-          '
+    - name: Start Server
+      run: |
+        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
+          export NVM_DIR="$HOME/.nvm"
+          if [ -s "$NVM_DIR/nvm.sh" ]; then
+            . "$NVM_DIR/nvm.sh"
+          else 
+            echo "nvm.sh not found"
+            exit 1
+          fi
+          nvm use --lts
+          npm install -g pm2
+          pm2 stop all
+          pm2 start /var/www/backend/index.js --name backend
+        '
